/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  IsOptional,
  ValidateNested,
  MaxLength,
} from "class-validator";
import { FinancialCreateNestedManyWithoutUsersInput } from "./FinancialCreateNestedManyWithoutUsersInput";
import { Type } from "class-transformer";
import { InventoryCreateNestedManyWithoutUsersInput } from "./InventoryCreateNestedManyWithoutUsersInput";
import { PurchasingCreateNestedManyWithoutUsersInput } from "./PurchasingCreateNestedManyWithoutUsersInput";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { SalesCreateNestedManyWithoutUsersInput } from "./SalesCreateNestedManyWithoutUsersInput";

@InputType()
class UserCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: () => FinancialCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => FinancialCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => FinancialCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  financials?: FinancialCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: () => InventoryCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => InventoryCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => InventoryCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  inventories?: InventoryCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  password!: string;

  @ApiProperty({
    required: false,
    type: () => PurchasingCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => PurchasingCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => PurchasingCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  purchasings?: PurchasingCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: true,
  })
  @IsJSONValue()
  @Field(() => GraphQLJSON)
  roles!: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => SalesCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => SalesCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => SalesCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  salesItems?: SalesCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  username!: string;
}

export { UserCreateInput as UserCreateInput };
