/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  IsOptional,
  ValidateNested,
  MaxLength,
} from "class-validator";
import { FinancialUpdateManyWithoutUsersInput } from "./FinancialUpdateManyWithoutUsersInput";
import { Type } from "class-transformer";
import { InventoryUpdateManyWithoutUsersInput } from "./InventoryUpdateManyWithoutUsersInput";
import { PurchasingUpdateManyWithoutUsersInput } from "./PurchasingUpdateManyWithoutUsersInput";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { SalesUpdateManyWithoutUsersInput } from "./SalesUpdateManyWithoutUsersInput";

@InputType()
class UserUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: () => FinancialUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => FinancialUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => FinancialUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  financials?: FinancialUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: () => InventoryUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => InventoryUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => InventoryUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  inventories?: InventoryUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  password?: string;

  @ApiProperty({
    required: false,
    type: () => PurchasingUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => PurchasingUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => PurchasingUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  purchasings?: PurchasingUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  roles?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => SalesUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => SalesUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => SalesUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  salesItems?: SalesUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  username?: string;
}

export { UserUpdateInput as UserUpdateInput };
