/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { PurchasingService } from "../purchasing.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PurchasingCreateInput } from "./PurchasingCreateInput";
import { Purchasing } from "./Purchasing";
import { PurchasingFindManyArgs } from "./PurchasingFindManyArgs";
import { PurchasingWhereUniqueInput } from "./PurchasingWhereUniqueInput";
import { PurchasingUpdateInput } from "./PurchasingUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PurchasingControllerBase {
  constructor(
    protected readonly service: PurchasingService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Purchasing })
  @nestAccessControl.UseRoles({
    resource: "Purchasing",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createPurchasing(
    @common.Body() data: PurchasingCreateInput
  ): Promise<Purchasing> {
    return await this.service.createPurchasing({
      data: {
        ...data,

        inventory: data.inventory
          ? {
              connect: data.inventory,
            }
          : undefined,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,

        inventory: {
          select: {
            id: true,
          },
        },

        purchaseDate: true,
        quantityPurchased: true,
        totalCost: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Purchasing] })
  @ApiNestedQuery(PurchasingFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Purchasing",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async purchasings(@common.Req() request: Request): Promise<Purchasing[]> {
    const args = plainToClass(PurchasingFindManyArgs, request.query);
    return this.service.purchasings({
      ...args,
      select: {
        createdAt: true,
        id: true,

        inventory: {
          select: {
            id: true,
          },
        },

        purchaseDate: true,
        quantityPurchased: true,
        totalCost: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Purchasing })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Purchasing",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async purchasing(
    @common.Param() params: PurchasingWhereUniqueInput
  ): Promise<Purchasing | null> {
    const result = await this.service.purchasing({
      where: params,
      select: {
        createdAt: true,
        id: true,

        inventory: {
          select: {
            id: true,
          },
        },

        purchaseDate: true,
        quantityPurchased: true,
        totalCost: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Purchasing })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Purchasing",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updatePurchasing(
    @common.Param() params: PurchasingWhereUniqueInput,
    @common.Body() data: PurchasingUpdateInput
  ): Promise<Purchasing | null> {
    try {
      return await this.service.updatePurchasing({
        where: params,
        data: {
          ...data,

          inventory: data.inventory
            ? {
                connect: data.inventory,
              }
            : undefined,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,

          inventory: {
            select: {
              id: true,
            },
          },

          purchaseDate: true,
          quantityPurchased: true,
          totalCost: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Purchasing })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Purchasing",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deletePurchasing(
    @common.Param() params: PurchasingWhereUniqueInput
  ): Promise<Purchasing | null> {
    try {
      return await this.service.deletePurchasing({
        where: params,
        select: {
          createdAt: true,
          id: true,

          inventory: {
            select: {
              id: true,
            },
          },

          purchaseDate: true,
          quantityPurchased: true,
          totalCost: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
