/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { FinancialService } from "../financial.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { FinancialCreateInput } from "./FinancialCreateInput";
import { Financial } from "./Financial";
import { FinancialFindManyArgs } from "./FinancialFindManyArgs";
import { FinancialWhereUniqueInput } from "./FinancialWhereUniqueInput";
import { FinancialUpdateInput } from "./FinancialUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class FinancialControllerBase {
  constructor(
    protected readonly service: FinancialService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Financial })
  @nestAccessControl.UseRoles({
    resource: "Financial",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createFinancial(
    @common.Body() data: FinancialCreateInput
  ): Promise<Financial> {
    return await this.service.createFinancial({
      data: {
        ...data,

        inventory: data.inventory
          ? {
              connect: data.inventory,
            }
          : undefined,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        amount: true,
        createdAt: true,
        id: true,

        inventory: {
          select: {
            id: true,
          },
        },

        transactionDate: true,
        transactionType: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Financial] })
  @ApiNestedQuery(FinancialFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Financial",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async financials(@common.Req() request: Request): Promise<Financial[]> {
    const args = plainToClass(FinancialFindManyArgs, request.query);
    return this.service.financials({
      ...args,
      select: {
        amount: true,
        createdAt: true,
        id: true,

        inventory: {
          select: {
            id: true,
          },
        },

        transactionDate: true,
        transactionType: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Financial })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Financial",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async financial(
    @common.Param() params: FinancialWhereUniqueInput
  ): Promise<Financial | null> {
    const result = await this.service.financial({
      where: params,
      select: {
        amount: true,
        createdAt: true,
        id: true,

        inventory: {
          select: {
            id: true,
          },
        },

        transactionDate: true,
        transactionType: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Financial })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Financial",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateFinancial(
    @common.Param() params: FinancialWhereUniqueInput,
    @common.Body() data: FinancialUpdateInput
  ): Promise<Financial | null> {
    try {
      return await this.service.updateFinancial({
        where: params,
        data: {
          ...data,

          inventory: data.inventory
            ? {
                connect: data.inventory,
              }
            : undefined,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          amount: true,
          createdAt: true,
          id: true,

          inventory: {
            select: {
              id: true,
            },
          },

          transactionDate: true,
          transactionType: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Financial })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Financial",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteFinancial(
    @common.Param() params: FinancialWhereUniqueInput
  ): Promise<Financial | null> {
    try {
      return await this.service.deleteFinancial({
        where: params,
        select: {
          amount: true,
          createdAt: true,
          id: true,

          inventory: {
            select: {
              id: true,
            },
          },

          transactionDate: true,
          transactionType: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
